### ISSUE TITLE
Return value of Phpro\SoapClient\Soap\SoapClientFactory::factory() must be an instance of Phpro\SoapClient\Soap\SoapClient, instance of VCR\Util\SoapClient returned

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#124]
Related: #84.

When running unit tests, which have php-vcr attached, I'm getting the following error from the first test:

```sh
TypeError: Return value of Phpro\SoapClient\Soap\SoapClientFactory::factory() must be an instance of Phpro\SoapClient\Soap\SoapClient, instance of VCR\Util\SoapClient returned
```

My php-vcr config in my bootstrap:

```php
// Configure and turn on PHP-VCR.
VCR::configure()->setStorage('json');
VCR::configure()->enableLibraryHooks(['soap']);
if (USE_TEST_API) {
    VCR::configure()->setCassettePath('tests/fixtures/vcrTest');
} else {
    VCR::configure()->setCassettePath('tests/fixtures/vcr');
}
VCR::turnOn();
```

If I change the library hook to be `curl`, then the tests all run and pass fine, but nothing gets stored in the php-vcr cassettes (i.e. it doesn't appear to be listening).

I'm using the default Handler (SoapHandle), and soap-client `dev-master`.

I didn't get the issue when I was using soap-client 0.3, so I suspect the addition of strict types / return type declarations since then may be the cause.

Removing the return type from `Phpro\SoapClient\Soap\SoapClientFactory::factory` allows the tests to run (though in my case, the cassette is still blank).

**Comment by veewee** [comment]
That will indeed cause an issue. 
As suggested in #84, I would suggest you to use the curl library hook and use the Http handle instead of the SoapHandle. In the future we will try to move away from ext-soap anyways.
In the meantime we can indeed drop the typehint of the factory.

**Comment by killua99** [comment]
I'm working with the Http\Adapter\Guzzle6\Client and HttPlugWsdlProvider still I do not get the vcr to save the files.

Could you update example tests to run with the current state of the codes? I think I'm missing something that would be small but hard to capture.

**Comment by killua99** [comment]
Well keeping working with this, I'm not sure how to make this project work with php-vcr.

This are some traces.

```Invalid exception returned from Guzzle6
 /www/ac-components/woocommerce-sagex3/vendor/phpro/soap-client/src/Phpro/SoapClient/Exception/WsdlException.php:31
 /www/ac-components/woocommerce-sagex3/vendor/phpro/soap-client/src/Phpro/SoapClient/Wsdl/Provider/HttPlugWsdlProvider.php:90
 /www/ac-components/woocommerce-sagex3/vendor/phpro/soap-client/src/Phpro/SoapClient/ClientBuilder.php:196
 /www/ac-components/woocommerce-sagex3/includes/Resources/class-clientbuilder.php:70
 /www/ac-components/woocommerce-sagex3/includes/Resources/class-clientbuilder.php:94
 /www/ac-components/woocommerce-sagex3/tests/test-products.php:22```

``` Caused by
 BadMethodCallException: Invalid http request. No cassette inserted. Please make sure to insert a cassette in your unit test using VCR::insertCassette('name');
 
 /www/ac-components/woocommerce-sagex3/vendor/php-vcr/php-vcr/src/VCR/Videorecorder.php:213
 /www/ac-components/woocommerce-sagex3/vendor/php-vcr/php-vcr/src/VCR/Videorecorder.php:291
 /www/ac-components/woocommerce-sagex3/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/CurlHook.php:203
 /www/ac-components/woocommerce-sagex3/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/CurlHook.php:257
 /www/ac-components/woocommerce-sagex3/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/CurlHook.php:150
 /www/ac-components/woocommerce-sagex3/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:106
 /www/ac-components/woocommerce-sagex3/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:123
 /www/ac-components/woocommerce-sagex3/vendor/guzzlehttp```

The bootstrap setup:

```		\VCR\VCR::configure()
				->enableLibraryHooks( [ 'curl' ] )
				->setCassettePath( 'tests/fixtures' );
		\VCR\VCR::turnOn();
		\VCR\VCR::turnOff();```

and the test has:

```	/**
	 * @since 0.0.1
	 *
	 * @vcr product-fetch.yml
	 */
	public function testProductFetch() {```

This is the way I create my Client the clientbuilder:

https://gist.github.com/killua99/a2bbd99838e60bf695c3f875db43e656

**Comment by veewee** [comment]
Hi @killua99,

Did you enable the VCR listener for phpunit? Otherwise the "@vcr" annotation won't work. You also turnOff VCR in the bootstrap file.

A sample on how the VCR can be used with guzzle6 can be found in this demo repo: (which is more about showing the code-generation tools, but also contains phpvcr)
https://github.com/veewee/demo-soap-client

**Comment by killua99** [comment]
Hi veewee thanks for the demo I did some advance in the meantime I wrote this issue.

I deleted the turnOff method.

And the test were recording right if I input directly the cassette now I might try the vcr listener.

In the other matter. Your demo doesn't have a src folder is that meant to be like that, or was just an error, since I can't see the weather class to check the rest of the demo.

One last thing, just if you know nothing 100% related to the issue, do you know why whenever the Response doesn't has a Content-Lenght and the transfer encoding is chunked the curl PHP library hangs ? (I was searching the entire google to know why and how to fix it)

**Comment by veewee** [comment]
Hi @killua99,

To create a src folder, you need to follow the readme steps in that repo. That is done on purpose.
Chunked should be working if you are using curl. In the regular ext-soap library that is not implemented yet.

**Comment by killua99** [comment]
Oh that wizard is new!

I'll try it out, do you need some help debugging or something, I'm working right now with an old soap_1_1 client that for instance all the soapAction are empty but it require a string on it.

**Comment by veewee** [comment]
Not sure what you want to debug? Maybe you can create a separate issue if something is wrong?

**Comment by hniirane** [comment]
The actual error caused by phpvcr:
```
TypeError: Return value of Phpro\SoapClient\Soap\SoapClientFactory::factory() must be an instance of Phpro\SoapClient\Soap\SoapClient, instance of VCR\Util\SoapClient returned
```

Is due to the fact that phpvcr overrides calls to `new SoapClient()` so the https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Soap/SoapClientFactory.php#L56 Call returns overridden `VCR\Util\SoapClient` instance instead of the required `Phpro\SoapClient\Soap\SoapClient`. This can be fixed easily by using the fully qualified name when creating the class:
```diff
-         return new SoapClient($wsdl, $options);
+        return new \Phpro\SoapClient\Soap\SoapClient($wsdl, $options);
```
Then the phpvcr correctly overrides \SoapClient in `class SoapClient extends \SoapClient` and not the `new SoapClient()` call.

Should I prepare a PR for this oneliner or will it not get implemented?
