### ISSUE TITLE
Problem with extended classes

### ISSUE THREAD

**Issue by amaccis** [phpro/soap-client#156]
Hi.
I need to consume a soap ws with the following wsdl (this is an excerpt):
```
<xs:complexType name="objectResponse">
  <xs:complexContent>
    <xs:extension base="tns:serviceResponse">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="object" nillable="true" type="tns:object"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```
By generating my classes, clearly, I got two classes:
- objectResponse (that extends serviceResponse);
- serviceResponse.

but the xml created by the clientBuilder considers only the class objectResponse, as if it does not extend serviceResponse.
What am I doing wrong?
Thanks!

**Comment by amaccis** [comment]
Solved, it was not a soap-client issue.

**Comment by smartydroid** [comment]
> Solved, it was not a soap-client issue.

@amaccis Hi, I have encountered similar problems. How do you solve it? Thank you very much.

**Comment by dxvargas** [comment]
I have the same question as @amaccis  and the same question as @smartydroid .

**Comment by veewee** [comment]
The extension information is not coming out of ext-soap at this point.
You'll have to use the [ExtendAssembler](https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#extendassembler) for this and configure it manually.

**Comment by veewee** [comment]
Hello,

We noticed this issue got reported many times and want to tackle it at its core!
Therefore, we've planned a [project that will work on better types support](https://github.com/php-soap/.github/blob/main/PROJECTS.md#better-types).
It’s going to be a huge project, so we are looking for ways to make development possible during our business hours instead of in our developers precious spare time.

In case you want this feature as badly as us: **[find out how you can support this project here 💚](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md)**!
