### ISSUE TITLE
Check if zend code is installed

### ISSUE THREAD

**Issue by janvernieuwe** [phpro/soap-client#162]
A small ease of use improvement.

Before running commands that need zend-code, quicky check if it is installed and display a usefull error message.

```
        if (!class_exists(ClassGenerator::class)) {
            $io->error(['zend-code not installed', 'composer require --dev zendframework/zend-code:^3.1.0']);

            return 0;
        }
```

Sample implementation for a single command, this needs to be centralised so all generating commands can use it.

**Comment by veewee** [comment]
I'dd suggest using a console command event listener for that: http://symfony.com/doc/current/components/console/events.html

This way you can add the check in a decentralized place and do some whitelist / blacklist stuff in the future. By calling the `$event->disableCommand()`, the application will not run the command and return a decent exit code: `\Symfony\Component\Console\Event\ConsoleCommandEvent::RETURN_CODE_DISABLED` instead of `0`

**Comment by janvernieuwe** [comment]
I think a basic check will be enough for now, it's mostly to catch that zend-code is not installed yet.
