### ISSUE TITLE
Error wihle creating SoapRequest

### ISSUE THREAD

**Issue by nikophil** [phpro/soap-client#195]
|    Q        |   A
|------------ | -----
| Version     | 0.7.7

Hello,

i'm facing a problem when trying to call my soap service (my webservice is a soap 1.1)
when i'm calling `\Phpro\SoapClient\Client::call()` i got this error:
`Argument 3 passed to Phpro\SoapClient\Soap\HttpBinding\SoapRequest::__construct() must be of the type string, null given`
This third argument is `$action`, but i can't find any way to provide this action

thanks for your help.

**Comment by veewee** [comment]
Hi @nikophil,

Can you provide some additional information about your integration?
- What runtime / code generation configuration are you using?
- Can you share the WSDL?
- which method are you calling
- a stack trace might be handy as well

**Comment by nikophil** [comment]
Hello @veewee 
thanks for your answer!

here is the `soap-config.php` generated:
```php
<?php

use Phpro\SoapClient\CodeGenerator\Assembler;
use Phpro\SoapClient\CodeGenerator\Config\Config;
use Phpro\SoapClient\CodeGenerator\Rules;

return Config::create()
    ->setWsdl('http://127.0.0.1:8000/EligibiliteAdresse_G3R10.wsdl')
    ->setTypeDestination('src/HTTP/Type')
    ->setTypeNamespace('App\HTTP\Type')
    ->setClientDestination('src/HTTP')
    ->setClientName('OrangeEligibiliteAdresseG3R10Client')
    ->setClientNamespace('App\HTTP')
    ->setClassMapDestination('src/HTTP')
    ->setClassMapName('OrangeEligibiliteAdresseG3R10Classmap')
    ->setClassMapNamespace('App\HTTP')
    ->addRule(new Rules\AssembleRule(new Assembler\GetterAssembler(new Assembler\GetterAssemblerOptions())))
    ->addRule(new Rules\AssembleRule(new Assembler\ImmutableSetterAssembler()))
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule(
                [
                    new Rules\AssembleRule(new Assembler\RequestAssembler()),
                    new Rules\AssembleRule(new Assembler\ConstructorAssembler()),
                ]
            ),
            '/request/i'
        )
    )
    ->addRule(
        new Rules\TypenameMatchesRule(
            new Rules\MultiRule(
                [
                    new Rules\AssembleRule(new Assembler\ResultAssembler()),
                ]
            ),
            '/response/i'
        )
    );
```

I was using the boilerplate code provided by the wizard for client / classmap / factory

The wsdl is not accessible publicly, here is the file
[EligibiliteAdresse_G3R10.txt](https://github.com/phpro/soap-client/files/2472491/EligibiliteAdresse_G3R10.txt)

here is the stack trace:
![capture du 2018-10-12 11-34-43](https://user-images.githubusercontent.com/10139766/46861492-1792d780-ce13-11e8-9647-da709549cc0e.png)

thanks for helping, don't hesitate if you need something more

**Comment by veewee** [comment]
Hi @nikophil,

It looks like this issue is related to the WSDL file: The binding does not contain a soap Action.
If you change the WSDL to the following, you do receive the action.

```diff
 	<!--  le binding definit un service accessible en mode document wrapped-literal -->
 	<wsdl:binding name="EligibiliteAdresseSoapBinding"
 		type="impl:EligibiliteAdresse">
 		<wsdl:operation name="getEligibiliteAdresse">
+			<wsdlsoap:operation soapAction="getEligibiliteAdresse" style="rpc" />
-			<wsdlsoap:operation />
 			<wsdl:input>
 				<wsdlsoap:body use="literal" />
 			</wsdl:input>
```
So you could fix this issue by changing the WSDL.
I've tested this with the internal soapclient:

```php
class Client extends \SoapClient
{
    public function __doRequest( $request, $location, $action, $version, $one_way = 0 ) {
     var_dump($action, $location);
     return parent::__doRequest($request, $location, $action, $version, $one_way);
    }
}

try {
    $client = new Client($wsdl, ['cache_wsdl' => WSDL_CACHE_NONE, 'trace' => true, 'soap_version' => SOAP_1_1]);
    $response = $client->getEligibiliteAdresse((object)['demande' => ['nom' => 'nom']]);

} catch (SoapFault $e) {
    var_dump($client->__getLastRequestHeaders(), $client->__getLastRequest());
}
```

One odd thing about this is that the __lastRequestHeaders() information is empty. 
According to the SOAP 1.1 specs, this should contain a SOAPAction header:

https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528

> An HTTP client MUST use this header field when issuing a SOAP HTTP Request.

> The presence and content of the SOAPAction header field can be used by servers such as firewalls to appropriately filter SOAP request messages in HTTP. The header field value of empty string ("") means that the intent of the SOAP message is provided by the HTTP Request-URI. No value means that there is no indication of the intent of the message.



When no action is available, this probably means that we are required to parse the request XML and detect the action name inside the body:

```xml
<SOAP-ENV:Body>
        <SOAP-ENV:getEligibiliteAdresse>
        </SOAP-ENV:getEligibiliteAdresse>
</SOAP-ENV:Body>
```

Scrolling through the ext-soap source, there are multiple situations in which we do not receive an actionName. 
I'll have to take a look what we could do from our side.

**Comment by nikophil** [comment]
:+1:
thanks a lot that's perfectly working...
actually yesterday i've found an ugly workaround by overriding `SoapClientFactory`  in order to return my own `SoapClient`wirth an empty action if the parameter was null...
now i can delete all of this :D

**Comment by drupol** [comment]
We also have this quite problematic issue.

We try to not alter too much the WSDL provided by the webservice, but this is becoming a real issue, we are making too much change in it in order to get it working properly. I'm running out of ideas :(

**Comment by veewee** [comment]
It's been a while since I looked into this issue. Does making the action nullable in our `SoapRequest` fix the issue?
Otherwise, the only solution I can think of is creating a native soap driver that can handle this situation, which is a lot of work or a wsdl changing middleware that adds this information into the wsdl. (which is error-prone)

**Comment by Vallevard** [comment]
Hi,
Today I was trying to implement this packages and also I faced the same issue.
The wsdl is private  and  also I cannot modify it because it's from a third party but below is a example what it's looks like:

```xml
<operation name="NameOfTheAction">
  <soap:operation/>
  <input name="SomeRequest">
      <soap:body use="literal"/>
   </input>
   <output name="SomeResponse">
     <soap:body use="literal"/>
   </output>
</operation>
```

```xml
<operation name="NameOfTheAction">
    <documentation> This service perform a .... </documentation>
    <input message="tns:SomeRequest"/>
    <output message="tns:SomeResponse"/>
</operation>
```

```xml
<message name="SomeRequest">
    <part name="body" element="xsd1:SomeRequest"/>
</message>
```

```xml
<element name="SomeRequest">
    <complexType>
        <sequence>
            <element minOccurs="0" name="Value1" maxOccurs="1" type="string"/>
            <element minOccurs="1" name="Value2" maxOccurs="1">
               <complexType>
                 <sequence>
                     <element minOccurs="1" name="Value2.1" maxOccurs="1" type="string"/>
                  </sequence>
              </complexType>
           </element>
      </sequence>
    </complexType>
</element>
```


I'm new in this (SOAP/WSDL), but trying to understand how this package works , I validate if the $action is null as below and the request was successfull (Of course it's just a workaround ) :

```php
    public function __doRequest($request, $location, $action, $version, $oneWay = 0)
    {
        $action = $action ? $action : "";
        $this->storedRequest = new SoapRequest($request, $location,  $action, $version, $oneWay);

        return $this->storedResponse ? $this->storedResponse->getResponse() : '';
    }
```

**Comment by veewee** [comment]
If it works, that would be a nice solution! Especially since you handle the null value inside the Soap client instead of the request class.
Care to create a PR with a test that covers this case?

**Comment by Vallevard** [comment]
Sorry, I'm not sure how to do test cases.

**Comment by drupol** [comment]
> It's been a while since I looked into this issue. Does making the action nullable in our `SoapRequest` fix the issue?
> Otherwise, the only solution I can think of is creating a native soap driver that can handle this situation, which is a lot of work or a wsdl changing middleware that adds this information into the wsdl. (which is error-prone)

I'll try this next Friday and provide some feedback. I might also provide a PR + test if needed.

**Comment by Kiachma** [comment]
Any updates on this issue?
I'm experiencing the same problem and @Vallevard :s solutions seem to solve it. 
I'd happily create a PR but I'm not that familiar with SOAP and, therefore, not sure how to write a test case for the solution.

**Comment by drupol** [comment]
I tried the proposed solution and another problem came up.
Unfortunately, because of that, the client decided to not use it anymore.
I wish I could dedicate more time, but it's definitely impossible within work time.
Sorry :-1:

**Comment by Kiachma** [comment]
That's a pity, we really need to solve this problem in order to proceed with a project at work. 
Let me know if there's anything I can do to help. I might be able to spend some time on the issue, but will probably need some guidance.
Thanks for an otherwise great library!

**Comment by veewee** [comment]
Hello @Kiachma,

The solution provided by @Vallevard above is fine to me, if it works.

```php
    public function __doRequest($request, $location, $action, $version, $oneWay = 0)
    {
        $action = $action ? $action : "";
        $this->storedRequest = new SoapRequest($request, $location,  $action, $version, $oneWay);

        return $this->storedResponse ? $this->storedResponse->getResponse() : '';
    }
```

However, we'll need a prove that it actually works.
Because not sending an action is not according to the soap spec (but might work).

So what I propose is to create a pr that:

- contains that code snippet above
- provides a minimal WSDL which we can test this specific issue on. [Examples](https://github.com/phpro/soap-client/tree/master/test/fixtures/wsdl)
- provide a functional test case that covers this issue. [Examples](https://github.com/phpro/soap-client/tree/master/test/PhproTest/SoapClient/Functional/ExtSoap/Encoding)

If your webservice happens to be a public or non secret one, Feel free to share it to me (can also be privately shared).
Maybe we can find a better alternate solution as well.

Let me know if you have any questions and hope to see a solution as well :)

**Comment by veewee** [comment]
Closing this issue.
Since php currently has strict types on the SoapClient, action must always be a string.
The solutions provided above will likely fail in newer php versions.
If you are still facing this issue, it should be reported to php internals instead : the action should always be a string.
