### ISSUE TITLE
Unable to Generate Classes for attached WSDL

### ISSUE THREAD

**Issue by tezrosolutions** [phpro/soap-client#20]
I am trying to generate the classes for attached WSDL but it gives following error:

 **[SoapFault] SOAP-ERROR: Parsing WSDL: Unknown required WSDL extension 'http://www.w3.org/2006/05/addressing/wsdl'**

[score-seeker-v1-0.wsdl.zip](https://github.com/phpro/soap-client/files/670073/score-seeker-v1-0.wsdl.zip)

**Comment by veewee** [comment]
Hello @tezrosolutions,

This issue is not related to this package but to the php soapclient.
More information:

Your WSDL contains this line:
```
<wsaw:UsingAddressing wsdl:required="true"/>
```

This means that the PHP soapclient is required to load the WSAW extension, which is not implemented in PHP. You can try to set this value to "false" to let the error go away. I haven't found another solution for this. Maybe you have more luck googling a solution :)

Next, if you want to use WS Adressing, you'll have to extend the soapclient.
You could use a package like:

- https://github.com/robrichards/wse-php
- https://github.com/coopTilleuls/wse-php

More information about similar issues:

- https://bugs.php.net/bug.php?id=46130
- http://stackoverflow.com/questions/16805488/php-soapclient-unknown-required-wsdl-extension

I'll also open another issue to add support for SoapClient extensions so that e.g. WSE can be enabled easily by configuration in a future version.
