### ISSUE TITLE
xsd:dateTime

### ISSUE THREAD

**Issue by DaveWeissDotNet** [phpro/soap-client#216]
There seems to be a general issue with xsd:dateTime in the standard php SOAP client. See [this link ](https://bugs.php.net/bug.php?id=44383).

Is there any way to get around this? I am using your library, and it is awesome - I just can't seem to figure this one issue out.

**Comment by veewee** [comment]
Hello,

Thanks for reporting!

I am a bit confused because of the issue you've linked. It states that there is an issue in the soapserver class and we are only providing a client implementation in this package. If there is an issue in the server, it needs to be solved in there.

We are using type converters to convert date strings into datetime objects. More information about that can be found here: https://github.com/phpro/soap-client/blob/master/docs/type-converter.md

You can locally overwrite the default datetime converter as a temporary workaround to  handle this issue.

**Comment by DaveWeissDotNet** [comment]
I figured it out... That stumped me for about a week.
