### ISSUE TITLE
Wssemiddleware not working

### ISSUE THREAD

**Issue by ilicmsreten** [phpro/soap-client#229]
|    Q        |   A
|------------ | -----
| Version     | 1.0.1

### Support Question

Hi I have a problem with https://github.com/phpro/soap-client/blob/master/docs/middlewares.md#wssemiddleware, because my middleware is not applied, so I can't auth to the server and always getting the error `SSL certificate problem: certificate has expired` with or without middleware in code

```
<?php
declare(strict_types=1);

namespace App\Soap;

use Http\Adapter\Guzzle6\Client;
use Phpro\SoapClient\Middleware\WsseMiddleware;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapEngineFactory;
use Phpro\SoapClient\Soap\Driver\ExtSoap\ExtSoapOptions;
use Phpro\SoapClient\Soap\Handler\HttPlugHandle;
use Symfony\Component\EventDispatcher\EventDispatcher;

final class FPClientFactory
{

    public static function factory(string $wsdl): FPClient
    {

        $handler = HttPlugHandle::createForClient(
            Client::createWithConfig([
            ])
        );
        $midd = new WsseMiddleware(
            __DIR__ . '/../path_to.pkey',
            __DIR__ . '/../public.pub'
        );
        $midd->withTimestamp(30000);
        $handler->addMiddleware($midd);

        $engine = ExtSoapEngineFactory::fromOptionsWithHandler(
            ExtSoapOptions::defaults($wsdl, [
            ]),
            $handler
        );

        $eventDispatcher = new EventDispatcher();

        return new FPClient($engine, $eventDispatcher);
    }
}
```

After this, I just call some method on `FPClient` and get the error. So why middleware is not applied, or how to set to this code works

**Comment by veewee** [comment]
Hello @ilicmsreten,

The configuration seems correct at first sight.
Since you are getting the error `SSL certificate problem: certificate has expired `:

* Can you verify that the key pairs you are adding to wsse are not expired?
* Can you verify that the curl ca is not expired?
* Can you verify that the https certificate of the host is not expired?

Can you also paste me what the request looks like before sending it to the server?
You can do this by e.g. using https://github.com/php-http/logger-plugin
Or you could create your own middleware for that purpose.

**Comment by ilicmsreten** [comment]
@veewee it's my fault. The problem was with the `location` config parameter. So please close this issue
