### ISSUE TITLE
Use soap-client as soap server

### ISSUE THREAD

**Issue by dxvargas** [phpro/soap-client#243]
|    Q        |   A
|------------ | -----
| Version     | 1.0.2

### Support Question

We would also want to use this library to receive back notifications from the webservice.
We have a different WSDL for these notifications. When using this WSDL to generate the client we get a... client.
Actually all the generated types seem useful. Any suggestions on how to use the generated code to receive requests (notifications) and send responses? Basically, how to use the client as a server!?

I was checking the driver and the encoder and decoder methods. But drivers are meant only to decode responses and encode requests.
We would need to decode a request (transforming the SOAP request into a PHP object). And to encode a response (transforming a PHP object into a SOAP response).

Would love to ear from you, what would be a good approach for this using soap-client library... or if I should just use other library!

**Comment by veewee** [comment]
Hallo @dxvargas,

As the name of this package might have implied, we only target the client implementation.
However, you might be able to reuse a lot of the stuff in this package.

A small list:
- Since the `\SoapServer` also accepts `classmap` and  `typemap`, it is perfectly possible to use the generated types - without the need of the driver system. (The driver system is a hack on top of the SoapClient to make it easier to accept other soap implementations that don't rely on ext-soap in the future - but the current ext-soap driver system is just using the build-in stuff from ext-soap)
- You could use the `ExtSoapOptionsResolverFactory` to convert classmaps and typemaps to `\SoapServer` construct `$options`.
- You could use the `ExtSoapMetadata` to parse your server WSDL and you may even build some code generation tool to generate the server class.
- You won't be able to reuse the middleware system etc. But you could write something on top of the `SoapServer::handle()` to allow server-side middleware (PSR-15 style). In this case you could reuse some of the `HttpBinding` part.

So the possibilities are there, but it's not something we will be building ;)
Of course there are also other SOAP packages available on github which do include a server. But that's up to you.

**Comment by ademarco** [comment]
Thank you for your input @veewee! So, given that we have generated a classmap called `NotificationClassmap` from the server-side WSDL, would something like the following work?

```php
        ...
        $options = ExtSoapOptionsResolverFactory::create()->resolve([
            'classmap' => NotificationClassmap::getCollection(),
        ]);
        $server = new \SoapServer($wsdl, $options);
        $server->setObject($handler);
        $server->handle();
  ```

When an incoming request will reach our application the `$handler` service will receive the request as a PHP object, since we told `\SoapServer` how to convert the raw XML into a PHP object via the `classmap` option.

Is that correct?

**Comment by veewee** [comment]
That is indeed how I assume it will work. But I haven't tested it.

**Comment by ademarco** [comment]
For the record: this worked as expected.

**Comment by veewee** [comment]
Now that I think of it, that is basically how our `ExtSoapServerHandler` works.
https://github.com/phpro/soap-client/blob/master/docs/handlers/ext-soap/local-server.md

(We just don't use typemap / classmap in there - but as you mention : it is possible)
