### ISSUE TITLE
Symfony 4.3 deprecations and soap-client

### ISSUE THREAD

**Issue by abenamer** [phpro/soap-client#249]
|    Q        |   A
|------------ | -----
| Version     | 1.0.4

### Support Question

I'm seeing the following error message: 
[info] User Deprecated: The "Phpro\SoapClient\Event\ResponseEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.

Looks like Symfony 4.x and soap-client aren't exactly happy with each other. Any suggestions?

**Comment by veewee** [comment]
We are currently supporting Symfony 2.8 to 4.x.
This package will still keep on working untill Symfony 5.0 removes the Event class.
At that point, we should be bumping to a minimum version Symfony 4.3.

Now it's to early to bump to that version, since it is only out for a month.
Unless you have an alternative suggestion I suggest you just ignore the deprecation warning in your logs.

**Comment by crashev** [comment]
Any update here?

**Comment by Reverze** [comment]
When a fixes can be expected?

**Comment by veewee** [comment]
We would surely accept a well-thought-out PR for this.
