### ISSUE TITLE
Optional elements become required constructor arguments

### ISSUE THREAD

**Issue by hhoechtl** [phpro/soap-client#282]
#### Summary

Most APIs use `<element name="lengthInCM" minOccurs="0">` as optional arguments. When generating code, those elements become required constructor arguments in the type classes.

#### How to reproduce

Generate a client from https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/3.0/geschaeftskundenversand-api-3.0.wsdl 
All optional arguments with `minOccurs=0` will become mandatory constructor arguments.

#### Expected behavior

Elements flagged as `minOccurs=0` should be optional arguments `$elementName = null` in the constructor of the type.

**Comment by qr** [comment]
Same problem for me

**Comment by mwolff-fn** [comment]
Same here. Also, I would expect the generated code to be sensitive to the "nillable" attribute as well.

As of v1.2.0, the following WSDL snippet...
`<element name="id" type="ns9:long" minOccurs="0" maxOccurs="1" nillable="true"/>`

...will result in:
`public function __construct(int $id)`

So per WSDL the property "id" can either be left out or explicitly be set to null. In the generated PHP class, I have to provide an integer.

I would expect the following code to be generated whenever minOccurs="0" or nillable="true" are present:
`public function __construct(?int $id)`

**Comment by veewee** [comment]
Sadly, this xsd information is not available within ext-soap.

**Comment by stiivo** [comment]
Wouldn't it make sense to implement a config setting which disables constructor parameters completely and let the user decide about the parameters which have to be set?

**Comment by veewee** [comment]
@stiivo : you can already do that by specificying not to use type hints in the `ConstructorAssemblerOptions` or by not using the `ConstructorAssembler` altogether.

The issue here is that currently we do not know about min or max occurences, since ext-soap doesn't give use that information. The only thing we can do is parsing the metadata from the WSDL manually and provide that information to the code generation part, so that we can improve code generation for nullable types.

I am not sure how you see the solution you provided, but feel free to give us some code examples.

**Comment by rauanmayemir** [comment]
@veewee I've been using WsdlToPhp: https://github.com/WsdlToPhp/PackageGenerator.
It goes to great lengths to get all the types right and correctly generates bindings of practically any complexity: xsd extensions, enums, optionals. However, it lacks the ability to adjust and customize rules, assemblers, and the client methods part is less flexible (i.e I find this package's way of generating clients and methods much preferable).

I wish there were a way to marry these two approaches - this package for OO, flexible, maintainable SOAP and WsdlToPhp for deep understanding of the wsdl/xsd schema.

**Comment by rauanmayemir** [comment]
Btw, the way it validates input is use validation rules on setter. Basically, you can instantiate an entity with all nulls and then set what you need.

**Comment by veewee** [comment]
Thanks for the feedback @rauanmayemir 

I've set up a proof of concept using the goetas XSD reader to fetch all the metadata information this package works with internally. It is quite promising. I was able to load the basic information and to fill in a lot of the missing information.

However I currently lack the time to finish it. It's quite the work... Hope to find time to work on it again some day soon.

Untill then I strongly believe that this package already covers all the really important bits  of a soap integration. But agree that it can always be better :)

**Comment by rauanmayemir** [comment]
@veewee Do you have it somewhere under a branch? I'd love to tinker and get a better grasp on how everything works here.

**Comment by veewee** [comment]
@rauanmayemir  I pushed it to this repo : https://github.com/veewee/vanilla-soap-driver/

At the moment, it is a bit of a mess and it also contains some other things I wanted to test.

A good starting point to discover the types might be this console command:
https://github.com/veewee/vanilla-soap-driver/blob/master/src/Console/Command/ParseMetadataCommand.php

It will currently only work for WSDL files that dont contain include / imports and it might contain a lot of issues ;)

**Comment by veewee** [comment]
Hello,

We noticed this issue got reported many times and want to tackle it at its core!
Therefore, we've planned a [project that will work on better types support](https://github.com/php-soap/.github/blob/main/PROJECTS.md#better-types).
It’s going to be a huge project, so we are looking for ways to make development possible during our business hours instead of in our developers precious spare time.

In case you want this feature as badly as us: **[find out how you can support this project here 💚](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md)**!
