### ISSUE TITLE
Error while generating the Types

### ISSUE THREAD

**Issue by drupol** [phpro/soap-client#300]
Hi,

I'm using this library to build a client for an internal service.

However, I'm having an issue while building the types.

See here the different relevant config files and log files.

**Soap Client config file**: https://del.dog/ifingaivai.txt
**Log**: https://del.dog/mitevaluno.txt
**Console command**: `./vendor/bin/soap-client generate:types -o --config=config/soap-client-Adonis.php -vvv`

I succeeded to find which class is causing the issue and at the end of the processing, I noticed a singularity with the `File` type, 2 files are generated for it: `File.php` and `File.php.backup`

`File.php`: https://del.dog/ogruxalofi.txt
`File.php.backup`: https://del.dog/apamaristu.txt

It looks like the correct file is `File.php.backup` and that there are some missing stuff in `File.php`.

I don't know where to start to debug the issue, any hint/clue is very welcome.

|    Q        |   A
|------------ | -----
| Version     | 1.2.0

**Comment by veewee** [comment]
Hello @drupol,

Didn't dive into the warnings yet, bit wanted to give you some pointers.

The issue is caused by a duplicate type in the wsdl.
Ext-soap is not able to determine in which xsd namespace it lives, so for PHP they are all the same.

More info:
https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#duplicate-typenames

However that file is a bit out of date. Since v1, we try to put all properties of the duplicate types into 1 big type.
This is what you can see in the logs as "patching" and why the backup file is created.
It looks like it cannot merge constructors etc at this moment, so that could be an improvement.

However, I'dd like to fix this by creating an ext-soapless engine for this package. If only I had some more time ... ;)

**Comment by drupol** [comment]
Hello @veewee,

Thanks for replying so fast, much appreciated.

So, basically I don't have a lot of options here:

1. Find the duplicated type in the WSDL
2. Implement an "ext-soapless" engine

Regarding the point 1, I think I can manage it, it will be painful, but I think I might be able to find it. If you have any hint, clue, advises on how to proceed, please let me know!

Regarding the point 2, I might be able to help if I had more information and maybe already start doing something.

**Comment by veewee** [comment]
Hello @drupol,

You could try to fix the code generation and make sure the result works for you.
At this point, I think it is a matter of making sure that all properties are combined in the constructor.
From that point on, you can use the class with ALL properties (some of them will be null depending on what API you call). At least that will make your code work for now.


Finding the duplicate types can be done by iterating through the metadata of the engine and counting the names. The data can be found here:

```php
foreach ($engine->getMetadata()->getTypes() as $type) {
    $name = $type->getName();
}
```

I also built some small test scripts for myself. This contains a duplicate types checker: (hope it works for you, not documented yet!) 

https://bitbucket.org/verweto/wsdl-parser


The "ext-soapless" approach is still too absract at this point. I am planning to play around with the scripts above first to get a better idea on how to build it. The idea is to:

1. Build metadata map based on WSDL
2. Change code generation to make sure it works for both engines
3. Add encoding / decoding layer

(Don't be fooled by the small list, it takes up a lot of time as you can see in these abstract tests:
https://github.com/phpro/soap-client/tree/master/test/PhproTest/SoapClient/Integration/Soap/Engine

**Comment by drupol** [comment]
Dear @veewee ,

Thanks for the insights.

I tested your new package without any trouble.
However, it seems that no duplicates are found.
Let me copy paste here the debug log. Hold on.

**Comment by veewee** [comment]
Is it possible to share those WSDL / XSD files or is that not allowed?

**Comment by drupol** [comment]
Ok, I will let you know before lunch. Thanks!

**Comment by clegginabox** [comment]
Just going to piggy back on this instead of creating a new issue.

I have 4 WSDL's to work with, 1 is fine on it's own, 2 and 3 reference 4 by way of CommonTypes. The generator finds the CommonTypes as duplicates and has all kinda of errors during generation of the classes.

Is there any way to get around this?

This (https://github.com/goetas-webservices/xsd2php) will generate the correct classes but it's tied to JMS/Serializer which is too slow for my use case.

**Comment by veewee** [comment]
Hello @clegginabox,

See comments above for a way around it. There is no easy solution yet ...

**Comment by clegginabox** [comment]
Thanks for the quick response @veewee. My problem is slightly different. I will open another issue to explain. I've not had yet much of a chance to dig around in your code yet, so even just some pointers on how I could look into it or just so that you're aware of a potential improvement.

**Comment by veewee** [comment]
Linking this one to #227 as well

**Comment by veewee** [comment]
Moving on in the PR issue.
