### ISSUE TITLE
Change getter assembler prefix to "is" for boolean properties?

### ISSUE THREAD

**Issue by GaryJones** [phpro/soap-client#31]
[This line](https://github.com/phpro/soap-client/blob/8229e08c33288960b57f9556ac5292a4644afcb5/src/Phpro/SoapClient/CodeGenerator/Assembler/GetterAssembler.php#L38) blindly adds `get` as the method name prefix. Could there be a check for the property type, and if it's a boolean, change it to `is`?

Drawback: Some boolean property getters may read better with `has` or `can` prefixes.

**Comment by veewee** [comment]
That sure is a possibility. Since this is a coding preference, I was thinking about optionally adding a map of method conversion rules so that you can get control about how the code gets generated.

Some references to similar questions in other projects:
- https://github.com/doctrine/doctrine2/issues/2987
- https://phpmd.org/rules/naming.html#booleangetmethodname

**Comment by jurbar** [comment]
see pr #52

**Comment by veewee** [comment]
Fixed in #52
