### ISSUE TITLE
How to extending base types

### ISSUE THREAD

**Issue by gitlog** [phpro/soap-client#311]
|    Q        |   A
|------------ | -----
| Version     | 1.2.0

### Support Question

How to set base type on generate types https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#extendassembler

Example extending base types

```xml

<xs:complexType name="LegalRef">
  <xs:complexContent mixed="false">
    <xs:extension base="tns:Ref">
      <xs:sequence>
        <xs:element name="code" nillable="true" type="xs:string"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```

Expected behavior
Response should be:

```php
class LegalRef extends Ref {

	private $code;
}
```

**Comment by veewee** [comment]
Something like this:

```php
new Rules\TypenameMatchesRule(
    new Rules\AssembleRule(new Assembler\ExtendAssembler('Ref')),
    '/^LegalRef$/'
)
```

You'll need to map those extends manually, since we don't get that information from ext-soap.

**Comment by drupol** [comment]
Pay attention that if you use this, you might most probably not be able to use the `FinalClassAssembler`.

**Comment by veewee** [comment]
Hello,

We noticed this issue got reported many times and want to tackle it at its core!
Therefore, we've planned a [project that will work on better types support](https://github.com/php-soap/.github/blob/main/PROJECTS.md#better-types).
It’s going to be a huge project, so we are looking for ways to make development possible during our business hours instead of in our developers precious spare time.

In case you want this feature as badly as us: **[find out how you can support this project here 💚](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md)**!
