### ISSUE TITLE
SSL connect error for ...

### ISSUE THREAD

**Issue by kamilstaniec** [phpro/soap-client#397]
|    Q        |   A
|------------ | -----
| Version     | x.y.z

Hello,
has a problem, namely when trying to call the method I get the error: _**SSL connect error for ...**_

**Nevertheless, all types are correctly mapped based on the configuration file.**

**Add that I am using a certificate and passphrase.**

_ClientFactory_:
```php
class ClientFactory
{
    public static function factory(string $wsdl)
    {
        $engine = DefaultEngineFactory::create(
            ExtSoapOptions::defaults($wsdl, [])
                ->withClassMap(Classmap::getCollection())
        );

        $eventDispatcher = new EventDispatcher();
        $caller = new EventDispatchingCaller(new EngineCaller($engine), $eventDispatcher);

        return new Client($caller);
    }
}
```
_Engine from config file:_

```php
$engine = DefaultEngineFactory::create(
    ExtSoapOptions::defaults('...', [
        'stream_context' => stream_context_create([
            'ssl' => [
                'local_cert' => '...',
                'passphrase' => '...',
            ],
        ]),
    ])->disableWsdlCache()
)
```
_Call ClientFactory:_

```php
$this->client = ClientFactory::factory($wsdlLink);
```

When extending the _factory_ method in the _ClientFactory_ class with the _$options_ parameter and assigning it to _ExtSoapOptions::defaults_:

```php
class ClientFactory
{
    public static function factory(string $wsdl, array $options = [])
    {
        $engine = DefaultEngineFactory::create(
            ExtSoapOptions::defaults($wsdl, $options)
                ->withClassMap(Classmap::getCollection())
        );

        $eventDispatcher = new EventDispatcher();
        $caller = new EventDispatchingCaller(new EngineCaller($engine), $eventDispatcher);

        return new Client($caller);
    }
}

// ...
// Call ClientFactory

$this->client = ClientFactory::factory($wsdlLink, [
    'stream_context' => stream_context_create([
        'ssl' => [
            'local_cert' => $cert,
            'passphrase' => $passphrase,
        ],
    ]),
]);
```
keeps getting _SSL connect error for ..._ even when tampering with the certificate path or passphrase as if neither of them were properly loaded.

Should I use some additional libraries?

Thanks for any help.

**Comment by veewee** [comment]
Hello,

We moved over to a new approach that uses a PSR-18 HTTP client instead of the built-in client.
Therefore, the stream_context you configured on the SoapClient options won't be used anymore.

There are 2 ways to solve this issue:

* Preferred : Configure the settings on the PSR-18 client you prefer (like guzzle or symfony http-client) and provide this client through a Psr18Transport. See https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Soap/DefaultEngineFactory.php#L23
* Less optimal: Use the [ExtSoapTransport](https://github.com/php-soap/ext-soap-engine/blob/main/src/Transport/ExtSoapClientTransport.php) directly instead. This way you can configure the stream context like in the example above. The downside here is that you'll need to create your own engine factory so that the client doesn't get initialized twice. (we might provide a custom factory in this package as well if it makes sense)

**Comment by kamilstaniec** [comment]
@veewee it works, thanks for your help!

**Comment by kamilstaniec** [comment]
@veewee 

One more thing, is there a solution for this type of error:
_**cvc-elt.4.3: Type 'ns1:Document' is not validly derived from the type definition, 'Document', of element 'ns2:Document'.**_

Thank you in advance.

**Comment by veewee** [comment]
Can you give some context?

**Comment by kamilstaniec** [comment]
@veewee when you try to call the method below:

```php

// ClientFactory class
class ClientFactory
{
    public static function factory(string $wsdl, array $options = []): Client {
        $transport = Psr18Transport::createForClient(
            new Client(['cert' => [$options['local_cert'], $options['passphrase']]])
        );

        $engine = DefaultEngineFactory::create(
            ExtSoapOptions::defaults($wsdl, [])->withClassMap(Classmap::getCollection()),
            $transport
        );

        $eventDispatcher = new EventDispatcher();
        $caller = new EventDispatchingCaller(new EngineCaller($engine), $eventDispatcher);

        return new Client($caller);
    }
}

// Call method from WSDL
$document = (new Document())
    ->withGrpHdr((new GroupHeader())
        ->withMsgId('abcdef12345')
        ->withCreDtTm(new DateTime()))
    ->withTransactionNumber($transactionNumber);

/** @var GetTransactionDetailsResponse $response */
$response = $this->client->getTransactionDetails(new GetTransactionDetailsRequest($document));
```

I am getting the aforementioned error. What can cause such an error?

**Comment by veewee** [comment]
Is this a PHP error or a SoapFault coming back from the server?
I don't know your service, so I can't really help you out here without diving into it.

**Comment by kamilstaniec** [comment]
@veewee sorry, this is error a SoapFault back from the server.

![image](https://user-images.githubusercontent.com/89976665/143494158-9f1e5cff-3e01-4178-af06-585f3bc322a1.png)

**Comment by veewee** [comment]
This is a validation error from the server most likely based on the input your are sending.

This is  most likely something you'll need to figure out yourself..

**Comment by kamilstaniec** [comment]
ok, thanks for your help.

**Comment by drupol** [comment]
Hi all,

Sorry to dig up such old topics, but I'm trying to figure out how to avoid creating the client within the static factory.

```
public static function factory(string $wsdl, array $options = []): Client {...}
```

To avoid this, I'm doing this:

```php
    final class EcasCertLoginClientFactory
{
    public static function factory(?ClientInterface $client = null, string $localCert, string $passPhrase): EcasCertLoginClient
    {
        $wsdl = 'https://url-to-wsdl';

        $client = $client ?? new PluginClient(
            Psr18ClientDiscovery::find(),
            [],
            [
                'cert' => [
                    $localCert,
                    $passPhrase
                ]
            ]
        );

        $engine = DefaultEngineFactory::create(
            ExtSoapOptions::defaults($wsdl, [])
                ->withClassMap(EcasCertLoginClassmap::getCollection()),
            Psr18Transport::createForClient($client)
        );

        $eventDispatcher = new EventDispatcher();
        $caller = new EventDispatchingCaller(new EngineCaller($engine), $eventDispatcher);

        return new XXXXX($caller);
    }
}
```

Do you think this is a valid option? I don't want to force users to use a specific HTTP client.

Second point, when I regenerate the classes, how can I modify the configuration to make sure it does not override those customizations?

Thanks!

**Comment by veewee** [comment]
Hello,

I'dd say, since the factory is very static code-wise, the generate client factory class is rather a boilerplate generator on which you can customize or that can be used as an example.
Especially if you want to do very custom things, as you are showing in your examples.

That is basically why we decided to add a `DefaultEngineFactory` that does a lot of the heavier engine creation boilerplate. The logic in there we can and will adjust in future versions so that you always have the best settings possible.

It probably costs a lot more time to create a custom factory generator than just adding a static one to your codebase.


Your factory is a bit odd though:

* If you pass a client, you still need to pass a certificate + passphrase (which are not used)
* If no client is passed, you try to find any psr-18 client - but pass the certificate options as if you knew exactly what client it was. That doesn't make much sense.

**Comment by drupol** [comment]
> I'dd say, since the factory is very static code-wise, the generate client factory class is rather a boilerplate generator on which you can customize or that can be used as an example. Especially if you want to do very custom things, as you are showing in your examples.

Great, thanks!

> Your factory is a bit odd though:

Oh yes definitely. I'm just testing out things right now, this is not going to be the real implementation... especially since I learned that there's a REST api available for the endpoint I'd like to use.

> 
>     * If you pass a client, you still need to pass a certificate + passphrase (which are not used)
> 
>     * If no client is passed, you try to find any psr-18 client - but pass the certificate options as if you knew exactly what client it was. That doesn't make much sense.

If I were to redo things, I would only pass a non-nullable ClientInterface in the constructor.

Thanks for the responsiveness !
