### ISSUE TITLE
How to generate all EnumTypes as classes with constants?

### ISSUE THREAD

**Issue by tgerakitis** [phpro/soap-client#403]
### Support Question

I looked through the docs and found several other issues:
* https://github.com/phpro/soap-client/issues/217
* https://github.com/phpro/soap-client/issues/172
* https://github.com/phpro/soap-client/issues/340

Until now, whenever I used a WSDL code generator, it would have the option to generate a class for each enum type and have the values as constants + some meta info.
Using those `classes::constants` to do your mapping and feed values to the service methods makes things much easier than having to take a look into `wsdl ` to see which values are allowed. 

Maybe I am mistaken, but so far I only saw possibilities to generate single enum types manually using an extensive class + configuration implementation. This seems fine for one or two types but becomes impossible when you have 200+ types to implement.

Which leads me to the question: Is there an option to automatically generate those enum type classes?

**Comment by veewee** [comment]
Hello @tgerakitis,

This currently is a known limitation of this package. Simply because ext-soap does not provide this information.

See https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#enumerations

I have been working on wsdls metadata parsing on various moments throughout the past year, but am a bit limited in spare time at the moment. Once I can parse the information into something this package can work with, it shouldn't be too hard to create either constants or possible a php8.1 enum object (if soap can encode/decode that).

However, at current pace... It might as well take another year before I get there. 

So for now, the short answer that it is not included.
The workable answer is, that you can parse xsd enumerations from wsdls yourself.
The long-term answer is that it's on the table, yet far from complete yet

**Comment by tgerakitis** [comment]
Understood, thank you  @veewee
