### ISSUE TITLE
Invalid return value MixedResult

### ISSUE THREAD

**Issue by sippsolutions** [phpro/soap-client#409]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.7.1

#### Summary

Calling a service leads to a TypeError if the SOAP service is not reachable.
`Fatal error:  Uncaught TypeError: Return value of SoapClient::xyz() must be an instance of XyzResponse, instance of Phpro\SoapClient\Type\MixedResult returned in SoapClient.php:170`
I had the issue when I accidentally forgot to connect to the VPN when testing the call.

Duplicates #345 which is closed.

#### Current behavior

A MixedResult is returned, but XyzResponse is used as typehint:
`public function xyz(\Xyz\Xyz $parameters) : \XyzResponse`
PHP triggers a Fatal error exiting the application.

#### How to reproduce

Generate a SOAP client with type hints/return types enabled.
Call a service using a WSDL with an invalid IP (for example http://99.44.55.66/xyz/?wsdl).

#### Expected behavior

A correct Response object (holding the error) should be returned or an Exception should be thrown.
Returning a MixedResult results in a Fatal error and therefor breaks the whole application.

**Comment by veewee** [comment]
Hello @sippsolutions,

Thanks for reporting!
The issue here is that ext-soap returns `null` without leaking any information about WHAT went wrong.

This is related to https://github.com/php-soap/ext-soap-engine/issues/7.
I already found a solution for timeouts, but not for other causes.

It is exactly why we use a PSR-18 HTTP client by default in v2 : by using a decent HTTP client, timeouts, 400-500 status codes, chunked encoding, ... can be transformed to the correct message automatically.  By ruling out the sucky ext-soap HTTP layer, you will get better error handling as well. 

So the best thing you can do if you are still on 1.7, is to use the httplug handle.

At this point, I still don't know if `NULL` returns are ALWAYS an indication of an error. If that's the case, we could add a simple null check - but it will still be quite meaningless.
It is still under investigation and might be fixed in `ext-soap-engine` if I (or anyone else) finds a solution.
If the solution is easy, we might also backport it to v1.7.x.

**Comment by sippsolutions** [comment]
Hi @veewee,

unfortunately we need to stay on PHP 7.4 for the next months, which v2.0 is not compatible with.
Can you explain what you mean by using the httplug handle? Can you provide a code example?

For anyone else finding this issue, I found a workaround which throws an exception instead of a fatal error for this case by adding a Subscriber to your dispatcher:

    /** @var ResponseEventSubscriber $responseEventSubscriber */
    $dispatcher->addSubscriber($responseEventSubscriber);

and for ResponseEventSubscriber.php:

    <?php
    
    declare(strict_types=1);
    
    namespace Xyz;
    
    use Magento\Framework\Exception\LocalizedException;
    use Phpro\SoapClient\Event\ResponseEvent;
    use Phpro\SoapClient\Events;
    use Phpro\SoapClient\Type\MixedResult;
    use Symfony\Component\EventDispatcher\EventSubscriberInterface;
    
    class ResponseEventSubscriber implements EventSubscriberInterface
    {
        /**
         * @param ResponseEvent $event
         */
        public function onClientResponse(ResponseEvent $event)
        {
            // @see https://github.com/phpro/soap-client/issues/409 (workaround)
            if ($event->getResponse() instanceof MixedResult) {
                throw new Exception('API call was not successful.');
            }
        }
    
        /**
         * @inheritDoc
         */
        public static function getSubscribedEvents(): array
        {
            return [
                ResponseEvent::class => 'onClientResponse', // I have no clue why this does not work :)
                Events::RESPONSE => 'onClientResponse', // This works until soap-client@2.0
            ];
        }
    }

**Comment by sippsolutions** [comment]
Hi @veewee,

unfortunately we need to stay on PHP 7.4 for the next months, which v2.0 is not compatible with.
Can you explain what you mean by using the httplug handle? Can you provide a code example?

For anyone else finding this issue, I found a workaround which throws an exception instead of a fatal error for this case by adding a Subscriber to your dispatcher:

    /** @var ResponseEventSubscriber $responseEventSubscriber */
    $dispatcher->addSubscriber($responseEventSubscriber);

and for ResponseEventSubscriber.php:

    <?php
    
    declare(strict_types=1);
    
    namespace Xyz;
    
    use Magento\Framework\Exception\LocalizedException;
    use Phpro\SoapClient\Event\ResponseEvent;
    use Phpro\SoapClient\Events;
    use Phpro\SoapClient\Type\MixedResult;
    use Symfony\Component\EventDispatcher\EventSubscriberInterface;
    
    class ResponseEventSubscriber implements EventSubscriberInterface
    {
        /**
         * @param ResponseEvent $event
         */
        public function onClientResponse(ResponseEvent $event)
        {
            // @see https://github.com/phpro/soap-client/issues/409 (workaround)
            if ($event->getResponse() instanceof MixedResult) {
                throw new Exception('API call was not successful.');
            }
        }
    
        /**
         * @inheritDoc
         */
        public static function getSubscribedEvents(): array
        {
            return [
                ResponseEvent::class => 'onClientResponse', // I have no clue why this does not work :)
                Events::RESPONSE => 'onClientResponse', // This works until soap-client@2.0
            ];
        }
    }

**Comment by veewee** [comment]
@sippsolutions 
See https://github.com/phpro/soap-client/blob/v1.7.1/docs/handlers/httplug.md
On 1.7.x you can use httplug in which you can create a PSR-18 HTTP client.
This will make sure to throw exceptions during HTTP issues.

**Comment by veewee** [comment]
Closing this issue since it is resolved.
For inspecting  / dealing with the underlying issue, you can keep track here https://github.com/php-soap/ext-soap-engine/issues/7

**Comment by sippsolutions** [comment]
@veewee IMO returning a MixedResult when the corresponding call expects a typed result is the problem here and should be changed even if there are workarounds as the most users will struggle to debug this issue or even find workarounds.
So I would change `$result = new MixedResult($result);` to something like `throw new MixedResultException($result);`, as returning a MixedResult when expecting a typed result object will always break the application.
I would therefor not consider this issue resolved, but it can be closed as we documented workarounds if you do not plan on fixing this.

**Comment by veewee** [comment]
Don't get me wrong: I get what you are saying and it is not ideal by far!

It is perfectly possible that the SOAP server returns scalar results like strings, integers, ... which result in a MixedResult. Throwing an exception there would be wrong and even problematic for those SOAP services. 

I am trying to get it fixed at the core in the `AbusedClient`, but there is just no way I can tell if null is actually a wrong result or not. At least I couldn't find it until this point.

The best solution here is to not use the built-in HTTP layer and instead go for something like a PSR-18 or httplug client. Which was always the recommended way and since v2 the default way. This fixes pretty much all of the issues you are facing. It is also documented here: https://github.com/php-soap/ext-soap-engine/#transports

Using the built-in way has tons of unfixed long-standing known issues: 
https://bugs.php.net/search.php?cmd=display&search_for=soap+http&x=0&y=0
Expect to have a bad time if you use it!

I am all in favour of using as strict types as possible. You'dd even expect SOAP to be strict as well, since it uses a WSDL. However, I've encountered quite some scenarios in which the results don't match the WSDL or only partially.
Besides that, ext-soap doesn't leak minOccurs and maxOccurs, making it very hard to get the generated types 100% correct.
So for SOAP I am currently veyr sceptical about setting the types ultra strict.
