### ISSUE TITLE
return-type: add null

### ISSUE THREAD

**Issue by michabbb** [phpro/soap-client#442]
|    Q        |   A
|------------ | -----
| Version     | v2.2.1

when using `withReturnType()` in the config, a return type will look like this:

https://github.com/phpro/soap-client/blob/9c616b677df4c7038a17a5c5390becadf3f7b55e/src/Phpro/SoapClient/CodeGenerator/Model/Property.php#L70

but in my case every return can also be null, so it would make more sense for me, to have this:

`return '?\\'.$this->namespace.'\\'.Normalizer::normalizeClassname($this->type);`

so with a leading `?`.

i looked into the https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#propertyassembler
but to me it looks like, i have to duplicate the whole property stuff to make this work.

yes i know, the easiest way would be **NOT** using return-types at all, but hey, PHP is becoming more and more
type-strict, so I really like to use it, wherever possible 😏 

@veewee maybe there is a better way, maybe i missed something. would be happy to get some advice here. thanks !!

**Comment by veewee** [comment]
Hello,

The problem here is that your properties most likely have a minOccur of 0.
Ext-soap does not provide that information to us:
https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#occurs

Currently, this issue can be avoided by not generating too strict types in the soap-client.

This issue has been reported a few times: #346, #231, #282, #344,  ...

Until we have a better way of getting the data back from the WSDL, there is no simple solution for this.
The best thing you can do, is making your own property assembler and use that one instead.

**Comment by michabbb** [comment]
@veewee on my search for an answer i have read this "copy&paste" answer 100 times 😏 
but if you would take 1 more minute, than you would realize, that this "feature" I am asking for has nothing to do with the stuff "ext-soap" is capable of. this is part of your framework and how "you" create properties.

I am just asking, if you would accept any kind of PR that would allow doing something like this:

`new PropertyAssembler(PropertyGenerator::VISIBILITY_PROTECTED, PropertyGenerator::ALLOW_NULL)`

so the return value always has as leading `?` .

if am not wrong, this shouldn´t be a big deal.

**Comment by veewee** [comment]
That would work, but it would cover up the actual issue behind a flag you need to be aware about.
By making ALL properties null, your static analyzer would remind you to always do a null-check before using any value, even though minOccurs could in fact be 1 and therefor not nullable.

Not a good solution IMO.

I'dd rather provide a solid solution than this "add a flag to work differently" solution that will result in me having to copy/paste the message above even more ;)

Nothing stops you from creating your own assembler and use that one instead though. It's not that big of a class.

**Comment by michabbb** [comment]
@veewee thanks for your quick answer. in general i agree, but when you work with ebay, many things become like hell 🙈 
there are objects like:

`$whatiReallyWant = $item->getABC()->getABC()->getABC()->getABC()->getABC()->getWhatiReallyWant()`

and instead of checking every single level, it´s just easier to write it this way:

`$whatiReallyWant = $item?->getABC()?->getABC()?->getABC()?->getABC()?->getABC()?->getWhatiReallyWant()`

so when `$whatiReallyWant`  is NULL, it´s okay, I don´t care which level exactly is NULL.

that´s the reason I am asking. but okay, I will try creating my own assembler!
thanks for your support and this fantastic package!

**Comment by veewee** [comment]
Hello,

We noticed this issue got reported many times and want to tackle it at its core!
Therefore, we've planned a [project that will work on better types support](https://github.com/php-soap/.github/blob/main/PROJECTS.md#better-types).
It’s going to be a huge project, so we are looking for ways to make development possible during our business hours instead of in our developers precious spare time.

In case you want this feature as badly as us: **[find out how you can support this project here 💚](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md)**!
