### ISSUE TITLE
Type Array is not well determined

### ISSUE THREAD

**Issue by TheoBiron** [phpro/soap-client#455]
Hello,

I started using your lib, which is really good, but i had an issue on the types generation.
I'm using a WSDL file from and external API. I don't know if the way it's written is good, but I can't really change it on my side anyway.
The problem is that in this file, it expects to have some array of entities, but the types generation only type them as the entity, not as an array.

Here, you can see that in the definition of the result, I expect an implementation of array `ArrayOf_tns2_Balance`:
![image](https://user-images.githubusercontent.com/7087053/210751099-9206689f-3818-49f7-bbaa-0a903458700d.png)

This implementation is defined here
![image](https://user-images.githubusercontent.com/7087053/210751247-236858e3-a42f-4f57-9e9d-f8028a15af62.png)

However, this is what i get when generating the types in the *Result.php file:
![image](https://user-images.githubusercontent.com/7087053/210751523-43d881de-2174-453b-874c-1fc90e445a4a.png)

Is there any way to specify that this should be an array ?

I looked at this answer https://github.com/phpro/soap-client/issues/346#issuecomment-785772037 , tried it with IteratorAssembler, PropertyAssembler,... but it doesn't work

**Comment by veewee** [comment]
Hello,

Ext-soap does not provide the information we need to determine it is an array.
https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#occurs

Currently, this issue can be avoided by not generating too strict types (for example by only using the docblock types on the properties - which will still be invalid, but wont trigger any TypeError). Another way is by using the IteratorAssembler (which doesnt work out for you)

This issue has been reported a few times: #346, #231, #282, #344,  ...

Until we have a better way of getting the data back from the WSDL, there is no simple solution for this.
However, we are working on a custom [WSDL reader project](https://github.com/php-soap/.github/blob/main/PROJECTS.md#better-types) that will allow us to fetch this information. Since it is an early wip - it is currently not open for use yet.

To speed things up, **[Find out how you can help out this project here 💚](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md)**
