### ISSUE TITLE
Where to get the basic types

### ISSUE THREAD

**Issue by Traineratwot** [phpro/soap-client#467]
Hello, tell me where to get the basic types such as Boolean Type,String Type, Array Type...

Do I really have to write them myself?

**Comment by veewee** [comment]
Hello,

Normally, you shouldn't have to write anything yourself for that.
From your question, I understand that the SOAP service wraps custom simple types around the xsd base types. Is that correct?

Would you mind sharing the WSDL so that I can take a closer look?

You might want to try the alpha version of 3.0 - it should eventually have better support for this case.

**Comment by Traineratwot** [comment]
this page with WSDL collection http://extgate.alean.ru:8082/webservice/ewebsvc.dll

wsdl: http://extgate.alean.ru:8082/webservice/ewebsvc.dll/wsdl/IewsServer

I use php 8.1
my composer.json
```json
{
	"name"    :"ay-tour/alean-sdk",
	"type"    :"library",
	"require" :{
		"php"                         :">= 8.0",
		"symfony/http-client"         :"^6.2",
		"nyholm/psr7"                 :"^1.8",
		"traineratwot/composer-config":"^1.2",
		"phpro/soap-client"           :"^2.4.0",
		"psr/log-implementation"      :"*",
		"traineratwot/cache"          :"^3.0",
		"laravie/parser": "^2.0",
		"traineratwot/xmltodict": "^1.1"
	},
	"autoload":{
		"psr-4":{
			"AyTour\\AleanSdk\\":"src/"
		}
	},
	"config"  :{
		"allow-plugins":{
			"traineratwot/composer-config":true,
			"php-http/discovery"          :true
		}
	},
	"extra"   :{
		"composer-config":{
			"namespace":"AleanSdk",
			"optional" :{
				"CACHE_PATH":"path to save loginToken"
			}
		}
	},
	"scripts" :{
		"composer-config-print" :"composer getAllConfigs",
		"composer-config-update":"composer configUpdate"
	},
	"require-dev": {
		"monolog/monolog": "^3.3"
	}
}

```

**Comment by veewee** [comment]
It looks like currently the `ClientMethodAssembler` is not supporting `MixedResult` types.
In this case, your WSDL returns simple base-types, which must be wrapped in a result:

See:

* https://github.com/phpro/soap-client/blob/439f92226e4c93a0663d843dcaf65d62b16de54a/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php#L64
* https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Type/MixedResult.php


Its not somtehing fixable in version 2, but I'm pretty sure we can find a good solution for soap-client v3.
Since your WSDL is only using scalar types, you might be better of by using the php-soap packages instead of this one until its fixed.

Example usage:
https://github.com/php-soap/ext-soap-engine#example-usage

**Comment by veewee** [comment]
FYI, I was able to fix pretty much everything for v3.
https://github.com/phpro/soap-client/pull/470

The newly generated client will look like this:
https://gist.github.com/veewee/d82531b5721e88b698bc4b6ae42eb304

Feel free to play around with it - the stable release won't be for soon though.
