### ISSUE TITLE
A property with a hyphen in the name

### ISSUE THREAD

**Issue by h4kuna** [phpro/soap-client#477]
### Bug Report

Hello,

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | both 2.4.2 and dev 3

#### Summary

[The wsdl](https://immobinetagenzie.immobinet.it/webservice.wsdl#op.id11) provide property `definizioni-listini` if i generate classes the property has name `definizioniListini`. But if I get response the assign to object is to property `definizioni-listini` instead of `definizioniListini`. And method is 
```php
    public function getDefinizioniListini(): ArrayOfDefinizioneListino
    {
        return $this->definizioniListini;
    }
```

#### Current behavior

Broken assign from soap response to generated class.

#### How to reproduce

See ![image](https://github.com/phpro/soap-client/assets/335722/64578366-84a8-4f02-9b6e-f8a4af31c64e)

#### Expected behavior

The property `definizioniListini` is filled.

**Comment by veewee** [comment]
Interesting.
Since PHP's soap extension is not able to fill it in for you, can you try solving it by creating a custom type converter for it instead?


Info:

* https://github.com/php-soap/ext-soap-engine/tree/main#typeconverter
* https://github.com/php-soap/ext-soap-engine/blob/main/src/Configuration/TypeConverter/TypeConverterInterface.php


Type info:

* namespace : `http://www.immobinet.it/wsdl/WebserviceModAgenziaBundle`
* type: `getDefinizioneListiniResponse`

**Comment by veewee** [comment]
It is not something we can deal with at the moment. Check #485 for more information.

**Comment by veewee** [comment]
Hello there @h4kuna ,

I wanted to get back to this issue:
We are finishing up v4 of the soap-client package which uses a new encoding system internally.
With this new system, you should be able to get around this issue more easily.

We are eager to receive some early feedback on this new release.
If you got some time, feel free to play around with the alpha version:


* Release: https://github.com/phpro/soap-client/releases/tag/4.0.0-alpha1
* Discussion: https://github.com/phpro/soap-client/discussions/527
