### ISSUE TITLE
A field is not correctly inserted in request

### ISSUE THREAD

**Issue by etcware** [phpro/soap-client#489]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no ???
| Version     | 3.1.0

#### Summary
My request must include a date in the field <dataRiferimento> in the format yyyy-mm-ddT00:00:00 but the encoded xml is as in the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://my-url.it/"><SOAP-ENV:Body><ns1:estraiPersona><dtoRicerca><codiceFiscale>xxxxxxxxxxxxxxxx</codiceFiscale><dataRiferimento/></dtoRicerca></ns1:estraiPersona></SOAP-ENV:Body></SOAP-ENV:Envelope>
```
So the server answer is: Unmarshalling Error

#### Expected behavior

I suppose there is an error in field encoding due to '-' or ':' character. The expected behavior is a request with the field correctly encoded:

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://my-url.it/"><SOAP-ENV:Body><ns1:estraiPersona><dtoRicerca><codiceFiscale>xxxxxxxxxxxxxxxx</codiceFiscale><dataRiferimento>2023-10-16T00:00:00</dataRiferimento></dtoRicerca></ns1:estraiPersona></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

**Comment by veewee** [comment]
Hello,

By default, ext-soap-engine registers the DateTimeTypeConverter. ([More info](https://github.com/php-soap/ext-soap-engine/tree/main#typeconverter))
I'm assuming you are not using a DateTimeImmutable?

See:
https://github.com/php-soap/ext-soap-engine/blob/e1d7a85ce19dbd83dafcf692f8716d09be359c74/src/Configuration/TypeConverter/DateTimeTypeConverter.php#L44-L50

As you can see, the provided input needs to be of type `DateTimeInterface`. If not, it results in an empty tag value.

In order to solve this, there are 2 options:

1. Provide a `DateTimeInterface`
2. Unregister the converter or provide your own one

**Comment by etcware** [comment]
thanks it works, I mistakenly assumed the date was a string
