### ISSUE TITLE
Error al usar el asistente usando URL del wsdl sin extension (.wsdl)

### ISSUE THREAD

**Issue by marcoortiz1995** [phpro/soap-client#498]
Estoy utilizando la siguiente url para utilizar un servicio ubicado en https://efirma.morelos.gob.mx/WSFirmaOficio?wsdl
 Al finalizar el wizard, obtengo el siguiente error:

In RuntimeException.php line 33:
                                                                   
  Could not load the DOM Document                                  
  [FATAL] : Opening and ending tag mismatch: hr line 5 and body    
   (76) on line 6,8                                                
  [FATAL] : Opening and ending tag mismatch: body line 3 and html  
   (76) on line 7,8                                                
  [FATAL] : Premature end of data in tag html line 1               
   (77) on line 8,1                                                
                                                                   

In RuntimeException.php line 23:
                                   
  Could not load the DOM Document

Intente copiar todo a un archivo en mi proyecto pero al usar el path de mi archivo wsdl,  obtengo el siguiente error:
In CurlFactory.php line 211:
                                                                                                                                          
  cURL error 3: URL rejected: Bad hostname (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for resources%5CWSDL%5CService.wsdl

Me pudieran ayudar, porfavor. gracias.

**Comment by veewee** [comment]
Hello,

Perdón por mi español. Sólo puedo dar respuestas en inglés.


Given the error, it seems like you are parsing an `HTML` file instead of a `WSDL` file. Hence the error.
Are you sure you are using the correct service endpoint? I am not able to load the provided link from my end.

If you want to parse a local file, you need to pass in a different WsdlLoader in the `CodeGeneratorEngineFactory` that is configured in your generated config file.

You could use 

```php
use Soap\Wsdl\Loader\FlatteningLoader;
use Soap\Wsdl\Loader\StreamWrapperLoader;

$loader = new FlatteningLoader(new StreamWrapperLoader());
```

See `$loader`:
https://github.com/phpro/soap-client/blob/60a663170f2b748a471e7bfd763ae30b20973ad3/src/Phpro/SoapClient/Soap/CodeGeneratorEngineFactory.php#L29-L35
