### ISSUE TITLE
Array complex type

### ISSUE THREAD

**Issue by davibennun** [phpro/soap-client#5]
Hi!
First, congrats for the package, really well written!

I have the following complex type on my wsdl file:
```
<xsd:complexType name="userIdsArray">
  <xsd:complexContent>
   <xsd:restriction base="SOAP-ENC:Array">
    <xsd:attribute ref="SOAP-ENC:arrayType" wsdl:arrayType="xsd:integer[]"/>
   </xsd:restriction>
  </xsd:complexContent>
 </xsd:complexType>
```

How I can load it without getting this error:
```
PHP Catchable fatal error:  Argument 3 passed to Phpro\SoapClient\Event\ResponseEvent::__construct() must be an instance of Phpro\SoapClient\Type\ResultInterface, array given, called in /vendor/phpro/soap-client/src/Phpro/SoapClient/Client.php on line 100 and defined in /vendor/phpro/soap-client/src/Phpro/SoapClient/Event/ResponseEvent.php on line 35
```

**Comment by veewee** [comment]
Hello @davibennun,

Thanks for reporting!
I understand that the SOAP method is returning an array directly? So there is no object with `ResponseInterface` available?

That is currently an issue. The code is expecting that the returned object implements the `ResultInterface` or `ResultProviderInterface`. I guess there should be some built-in types to wrap around the scalar PHP return types. Otherwise it won't be possible to call the method with the `Client::call()` method.

To fix this issue quickly, you could create your own `Client::call()` method that handles scalar return types.

**Comment by davibennun** [comment]
Oh I got it, I'm just not sure how to implement a custom ```Client::call()``` method, I guess I'll have to dig into xml parsing...
Thanks
