### ISSUE TITLE
Call to undefined method Phpro\SoapClient\CodeGenerator\Config\Config::__set_state()

### ISSUE THREAD

**Issue by arifinreinaldo** [phpro/soap-client#500]
|    Q        |   A
|------------ | -----
| Version     | 3.1.1

### Support Question
![image](https://github.com/phpro/soap-client/assets/5634753/1e3ce0b8-dbbf-4f5f-83d2-6ef3fd85b262)

I tried to do php artisan optimize but im stuck with this issue, already tried to do composer dump-autoload, cache clear, upgrade composer but still the same error. Already make sure the function is able to check also. But unfortunately still get this error, is there any advice? Thank you

**Comment by veewee** [comment]
I don't know much about Laravel, but there is no __set_state method on that class. So maybe your Laravel specific configuration is invalid?
That config class should be used to generate code, so not sure it should even be part of the Laravel configuration directly.

The exception you pasted is about having a closure somewhere in your configuration which is not allowed because it can't be serialized.

**Comment by arifinreinaldo** [comment]
Hi Veewee, thank you for your clue.

For the config in Laravel it shouldn't be put at the config/soap-client.php, you should place it on different location like dedicated Soap Folder. That way it wont affect the optimize process.

Thanks for the reply @veewee

**Comment by dutsik-p** [comment]
I strongly agree. this soap-client config file should not be placed in config dir. as this is a part of local development. it should not go into production as a part of config. it will be slowing down overall performance, in my case it is 5 times bigger then the rest of the config. and it is loaded on each request.
