### ISSUE TITLE
Soap Attachments

### ISSUE THREAD

**Issue by KDederichs** [phpro/soap-client#514]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Since I saw #27 was closed without resolution I wanted to ask again if there's a way to use SOAP attachments now with this library.
I'm working with an API that's relaying on SOAP attachments for both sending and receiving (which I both have to do) and this library not being able to handle this is a big headache.

If you don't plan on implementing it, could you maybe give me some pointers on how to do it myself using middleware maybe?

**Comment by veewee** [comment]
Hello @KDederichs,

The issue was not closed but it moved to a discussion:
https://github.com/phpro/soap-client/discussions/357

There currently is still no official middleware that can deal with SOAP attachments like SwA and MTOM.
I would love to have one that we can provide out of the box from here though!

The statements in the initial ticket still stands:

* We currently don't have any service to test this on nor any direct customer that has this use-case.
* The provided technical details are still valid:
  * Dealing with attachments would mean parsing multipart HTTP messages and storing those intermediate files in some kind of file-bag so that it can be fetched later on based on the XOP include (either automatically somehow or manually)
* My time for working on this project is rather limited. However, I'm lucky to be able to be hired for these kind of tasks. See : https://github.com/php-soap/.github/blob/main/HELPING_OUT.md for more details


The way I see it, there are some ways forward:

* You can do the hard groundwork like understanding the spec and figuring out how to structure this yourself for your specific project.
  * If you  would love to give this back to the community, I can always set up a project inside the [php-soap](https://github.com/php-soap) organisation where we can discuss code and ideas around this. I would rather be your soundboard than the one creating the code. (It would be nice to have an initial version where we can incrementally improve upon)
* You can reach out to me as described in https://github.com/php-soap/.github/blob/main/HELPING_OUT.md#let-us-do-your-implementation so that we can discuss your specific project and figure out a solution for you on a paid consultancy basis. There are 2 ways we could do this:
  * We do your implementation and make sure you are able to work with attachments of which we could extract a separate library later on.
  * We can see it as a sponsorship in which you donate this SOAP attachment feature to the community.


I'dd be happy to discuss this with you in more detail!

**Comment by KDederichs** [comment]
I'll shoot you an email.

**Comment by veewee** [comment]
In case you are still interested : We now provide an HTTP plugin for dealing with SOAP attachments (SWA and MTOM):
https://github.com/php-soap/psr18-attachments-middleware

Feel free to check it out and play around with it. All feedback is highly appreciated.

**Comment by KDederichs** [comment]
ah neat, I've been thinking about making the one I built public for a while now but guess that settles that.
Glad to see we came up with something similar I guess.

**Comment by veewee** [comment]
Consider it still experimental at the moment: it's been crafted against specs and not tested against real soap services yet. (Since I don't have access to any that accepts / sends attachments )
