### ISSUE TITLE
Better error messages for converters

### ISSUE THREAD

**Issue by janvernieuwe** [phpro/soap-client#60]
When for example a DateTimeConverter gets a null value, you get a very vague soap exception:

`SoapFault: SOAP-ERROR: Encoding: Error calling to_xml callback`

It's probably a good idea to check if the type can be converted, and throw a clearer exception then the default soap error.

This is probably the case for all converters.

**Comment by veewee** [comment]
As discussed: This will probably not be possible since the way ext-soap is implementing the type converters:

When the to_xml method throws an error:
https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Soap/TypeConverter/TypeConverterCollection.php#L111-L113

ext-soap will throw a completly different SoapFault which does not contain the actual error:
https://github.com/php/php-src/blob/1f924d75cbdeee92f1743ac9df978a160b925bf3/ext/soap/php_encoding.c#L611-L613

**Comment by veewee** [comment]
This won't be possible because of ext-soap

**Comment by igorsantos07** [comment]
Stumbled upon this trying to uncover what's going on with a request I'm trying to make. Any guidance on how to debug such errors, then?

**Comment by veewee** [comment]
We could e.g. add a check if the variable is an instance of `DateTime` and throw a regular exception instead. However: this won't be visible since ext-soap overrides the exception. Maybe it's a better idea to get it patched in php-src instead. :)
