### ISSUE TITLE
GuzzleWsdlProvider fills up tmp with cache files and keeps downloading WSDL file

### ISSUE THREAD

**Issue by veloxy** [phpro/soap-client#63]
Unless I'm missing something major, there seem to be a few issues in the [guzzle provider](https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Wsdl/Provider/GuzzleWsdlProvider.php#L92)

A random file is ALWAYS generated if `getLocation()` does not return anything, it causes the system tmp directory to be filled up with files such as `/tmp/phpro-soap-client-wsdluP5u2I` but also with WSDL cache files, (if `cache_wsdl` is on) because the cache is based on that file.

I'm not sure what the point of setting a location is, you'd have to create an empty file in advance or it will throw a `WsdlException`, after that it will keep rewriting that file every time a `SoapClient` is built.

A GET request is always done to retrieve the WSDL, there is nothing that prevents this. Ideally it should return a path to the cached WSDL file, but this would keep it cached forever due to lack of cache invalidation.

I currently don't see a fix other than building in a cache manager to handle cache correctly, ideally one implementing PSR-6 or PSR-16. A unique cache key could be generated from `$source`. This would make the `cache_wsdl` option rather useless though, you'd have 2 caching layers.

**Comment by veewee** [comment]
Hi @veloxy,

Thanks for creating an issue.

It is indeed best to always specify a location if you don't want your tmp folder to be poluted.

The location should indeed accept paths that don't exist yet. I am not sure why these lines were added:
https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/Wsdl/Provider/GuzzleWsdlProvider.php#L97-L99
Maybe it's better to check if the directory exists or something like that. So this is something that needs to be fixed.

In a first version, we've added a caching mechanism. But the idea is indeed to use the `cache_wsdl` instead as mentioned at https://github.com/phpro/soap-client/blob/master/docs/wsdl-providers.md#guzzlewsdlprovider. This way, you have the TTL to invalidate the cache or you can remove the cache files manually to invalidate. You'll only have one layer of cache instead of 2.

**Comment by veloxy** [comment]
Well, specifying a location and enabling `cache_wsdl` option would indeed provide caching but that does not prevent te provider from downloading the WSDL over and over again. Or am I missing something?

To fix that, the provider should return the location of the file when the file contains data. So it doesn't re-download the WSDL again for no reason.

**Comment by veewee** [comment]
Oh, I see what you mean now. That is indeed correct. We'll need a way to make sure the file doesn't get downloaded every single time the provide method is being called. We'll definitely need to fix that!

In the meantime you can use a custom provider instead.

**Comment by veloxy** [comment]
Yep, I'm not sure what the best way to fix it is, though. If you'd check the file for contents and return the path - you'd cache the WSDL indefinitely, and then we're back to the cache manager option. Not sure if you'd want to keep the WSDL cached forever.

**Comment by veewee** [comment]
Another option is to download the wsdl during a deploy (WsdlProvider) and use the local file during normal operations (Localprovider).

**Comment by veewee** [comment]
Moving on in the PR issue #305.
