### ISSUE TITLE
Response type

### ISSUE THREAD

**Issue by Ziabat** [phpro/soap-client#8]
How can I solve this problem "Argument 3 passed to Phpro\SoapClient\Event\ResponseEvent::__construct() must implement interface Phpro\SoapClient\Type\ResultInterface, instance of stdClass given" ?

**Comment by veewee** [comment]
It looks like your SOAP call is returning an instance of `stdClass` instead of an instance of `ResultInterface`. Maybe you did not create an object implementing the `ResultInterface` add this specific object to your `ClassMap`?

Another possibility is that your SOAP server is always returning native types instead of a custom XSD object. This is currently not supported yet.

**Comment by Ziabat** [comment]
Thank you
